name: 'PRs Helper'
description: 'A GitHub Action that easily helps you automatically manage PR'
author: 'xrkffgg'
branding:
  icon: 'message-square'
  color: 'blue'
inputs:
  actions:
    description: 'Action name'
  token:
    description: 'Github_token'
    default: ${{ github.token }}
runs:
  using: node12
  main: 'dist/index.js'
